
(()=>{'use strict';
const STORY_FACTS={version:'STORY-FACTS-20261004.8',lesson:'數學・分數比較',competition:{item:'比較 2/3 與 3/5',rule:'先舉手且答案、理由正確得兩分',studentGroup:1,awardedGroup:2,awardedPoints:2,group1:{answerCorrect:true,handOrder:2},group2:{answerCorrect:true,handOrder:1},knownScoringError:false},currentWorksheet:{item:'比較 3/4 與 5/8，說明理由'},concern:'自己的組別也答對、努力寫理由，卻沒有競賽得分，感覺努力不被算入'};
const META={app_version:'CLASS5-REFERENCE-REBASE-20261004.13',scenario_version:'SCN165-167-SCENE-STORY-20261004.11',core_version:'REFERENCE-CORE13-WITH-AUDITED-PATCHES-20261004.1',evidence_engine_version:'LOCAL-EVIDENCE-0.9.5-CONTEXT-DEV',reference_upstream:'LOCAL-EVIDENCE-0.6.1-FINAL-REFERENCE',dynamic_session_baseline:'DynamicAssessmentSession v0.6.1 FINAL REFERENCE',stimulus_contract_version:'2.0-dev',strategy_mapping_version:'STRATEGY-MAPPING-20261004.12-DEV',worksheet_task_version:'WORKSHEET-TEACHING-20261004.11',phone_cat_version:'PHONE-CAT-20261004.8',story_fact_version:STORY_FACTS.version,scoring_validated:false,scoring_anchor_review_required:true,animation_interaction_spec:'ANIMATION_INTERACTION_PRODUCTION_SPEC_v1.0_FINAL',deployment_target:'GitHub Pages / static hosting',local_only:true,api_used:false,llm_adapter_active:false,sound_control_present:true,voice_control_present:true,voice_input_enabled:'browser-conditional',ui_layout_version:'VIEWPORT-FIT-SCENES-20261004.8',scene_engine_version:'SCENE-20261004.8',dialogue_action_version:'DIALOGUE-ACTION-20261004.11',co_regulation_version:'CLASSROOM-REENTRY-20261004.13',s166_information_frame:'SCN166-RETROSPECTIVE-20261004.13'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], now=()=>performance.now();
const els={stage:$('#stage'),dock:$('#responseDock'),progress:$('#progressBar'),sceneTag:$('#sceneTag'),stateTag:$('#stateTag'),toast:$('#toast'),teacherBubble:$('#teacherBubble'),teacherText:$('#teacherBubbleText'),studentBubble:$('#studentBubble'),studentText:$('#studentBubbleText'),colleagueBubble:$('#colleagueBubble'),colleagueText:$('#colleagueBubbleText'),narration:$('#narration'),narrationText:$('#narrationText'),transition:$('#transitionOverlay'),transK:$('#transitionKicker'),transT:$('#transitionTitle'),transS:$('#transitionSub'),parentCall:$('#parentCall'),parentLine:$('#parentCurrentLine'),teacher:$('#teacher'),teacherHead:$('#teacherHead'),teacherArm:$('#teacherArm'),teacherMouth:$('#teacherMouth'),zian:$('#zian'),zianHead:$('#zianHead'),zianArm:$('#zianArm'),zianMouth:$('#zianMouth'),peerA:$('#peerA'),peerB:$('#peerB'),peerC:$('#peerC'),peerD:$('#peerD'),paperPlane:$('#paperPlane'),birdRig:$('#windowBirdRig'),bird:$('#windowBird'),birdWing:$('#windowBirdWing'),eraser:$('#eraser'),pencilArm:$('#pencilArm'),peerAPaper:$('#peerAPaper'),bag:$('#bagVisual'),plant:$('#plantVisual'),curtain:$('#curtainVisual'),book:$('#fallingBook'),subjectTeacher:$('#subjectTeacherActor'),callStage:$('#callStage'),callHistory:$('#callHistory'),openingCurtain:$('#openingCurtain'),bagPaper:$('#bagPaper'),poster:$('#posterHotspot'),clock:$('#clock'),bookcase:$('#bookcaseHotspot')};
const startedAt=now(), sessionId='SJT165-'+new Date().toISOString().replace(/\D/g,'').slice(0,14)+'-'+Math.random().toString(36).slice(2,7);
const state={supportEvents:[],supportCommitments:[],phase:'INTRO',interaction_window:'FREE_EXPLORE',sound:false,motion_paused:false,bag_down:false,book_down:false,end:null,completed:false,first_look:[],classroom_recovery:null,colleague_interaction:null,interactive_state:{bag:'upright',book:'upright'},parent_interaction:{history:[],history_presentation:'persistent-current-line',voice_control_uses:0,reply_engine_version:'PARENT-DIALOGUE-REFERENCE-WITH-CONTEXT-PATCHES-20261004.1',last_teacher_text:null,last_parent_rule:null},layout_changes:[],interaction_trace:[],event_log:[],responses:[],items:{165:{scenario_version:'SCN-165-CORE13-PC15',rubric_version:'CORE-1.3-ITEM165',formal:{},support_path:[],support_evidence:{},evidence_first_observed_stage:{},target_pattern_first_met_stage:'never',records:[]},166:{scenario_version:'SCN-166-CORE13-PC15',rubric_version:'CORE-1.3-ITEM166',formal:{},support_path:[],support_evidence:{},evidence_first_observed_stage:{},target_pattern_first_met_stage:'never',records:[]},167:{scenario_version:'SCN-167-CORE13-PC15',rubric_version:'CORE-1.3-ITEM167',formal:{},support_path:[],support_evidence:{},evidence_first_observed_stage:{},target_pattern_first_met_stage:'never',records:[],communication_trace:[]}}};
let phaseStarted=now(), lifeTimer=null,pairTimer=null,toastTimer=null,birdBusy=false,planeBusy=false;
function t(){return Math.round(now()-startedAt)}
function log(action,detail={}){state.event_log.push({t_ms:t(),event_type:detail.event_type||inferEventType(action),scene:state.phase,state:state.interaction_window,version:META.app_version,input_mode:detail.input_mode??null,action,...detail});}
function inferEventType(a){if(a==='state_change'||a==='session_start'||a==='session_complete')return'system_event';if(a==='response_submitted'||a==='communication_trace')return'assessment_response';if(a==='ambient_event'||a==='interaction')return'ambient_interaction';if(a==='transition')return'transition_event';return'narrative_interaction'}
function safe(s){return String(s??'').replace(/\s+/g,' ').trim()} function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setProgress(n){els.progress.style.width=Math.max(3,Math.min(100,n))+'%'}
function setPhase(phase,windowName,progress){document.body.classList.toggle('show-results',phase==='COMPLETE');document.body.classList.toggle('learning-active',phase==='T01_TEACHING');state.phase=phase;state.interaction_window=windowName;phaseStarted=now();els.stage.dataset.window=windowName;els.stateTag.textContent=({FREE_EXPLORE:'自由探索',LOCKED_STIMULUS_DELIVERY:'情境播放',ASSESSMENT_WAIT:'等待回應',MEDIATION_LOCKED:'引導中',POST_STORY_FREE:'情節延伸',TRANSITION:'轉場'})[windowName]||windowName;if(progress!=null)setProgress(progress);C5_SCENES.enter(API,phase);C5_REFINE.phase(API,phase);globalThis.C5_GUIDANCE?.render(API,state.student_dialogue166?.history.at(-1));log('state_change',{phase,interaction_window:windowName});}
function hideLanguage(){els.teacherBubble.classList.remove('show');els.studentBubble.classList.remove('show','near');els.colleagueBubble?.classList.remove('show')} function clearNarration(){els.narration.classList.remove('show')}
function narration(text,kicker='情境'){hideLanguage();els.narration.querySelector('.kicker').textContent=kicker;els.narrationText.textContent=text;els.narration.classList.add('show');log('narration_presented',{text})}
function showTeacher(text){hideLanguage();els.teacherText.textContent=text;els.teacherBubble.classList.add('show');speakActor(els.teacher,els.teacherMouth,1800);C5_REFINE.cue(API,'teacher',text);log('teacher_line_presented',{text});requestAnimationFrame(()=>C5_EXT.positionBubbles?.(API))}
function showStudent(text,near=false){document.querySelector('#studentBubble .who').textContent='子安';hideLanguage();els.studentText.textContent=text;els.studentBubble.classList.toggle('near',near);els.studentBubble.classList.add('show');speakActor(els.zian,els.zianMouth,Math.max(1300,Math.min(3300,text.length*72)));C5_REFINE.cue(API,'student',text);log('student_line_presented',{text});requestAnimationFrame(()=>C5_EXT.positionBubbles?.(API))}
function showColleague(text){hideLanguage();els.colleagueText.textContent=text;els.colleagueBubble.classList.add('show');if(els.subjectTeacher&&!state.motion_paused)classmateReact(els.subjectTeacher);C5_REFINE.cue(API,'colleague',text);log('colleague_line_presented',{text});requestAnimationFrame(()=>C5_EXT.positionBubbles?.(API))}
function showParent(text,index,meta={}){hideLanguage();els.parentLine.textContent=text;if(els.stage.classList.contains('phone-scene'))addCallLine('parent',text);else els.parentCall.classList.add('show');const entry={planned_action:meta.planned_action||null,t_ms:t(),role:'parent',index,text,rule_id:meta.rule_id||null,trigger_intents:meta.trigger_intents||[],responding_to:meta.responding_to||null};state.parent_interaction.history.push(entry);state.parent_interaction.last_parent_rule=entry.rule_id;log('parent_line_presented',{index,text,rule_id:entry.rule_id,trigger_intents:entry.trigger_intents})}
function hideParent(){els.parentCall.classList.remove('show')}
function addCallLine(role,text){if(!els.callHistory)return;const d=document.createElement('div');d.className='call-msg '+role;d.innerHTML=`<small>${role==='teacher'?'導師':'子安家長'}</small>${esc(text)}`;els.callHistory.appendChild(d);els.callHistory.scrollTop=els.callHistory.scrollHeight;C5_REFINE.phoneSpeaker(API,role);}
function presentUserUtterance(text){if(els.stage.classList.contains('phone-scene')){addCallLine('teacher',text);state.parent_interaction.last_teacher_text=text;state.parent_interaction.history.push({t_ms:t(),role:'teacher',text,stage:state.phase});log('teacher_phone_line_presented',{text});}else{showTeacher(text)}}
function toast(msg,ms=1700){clearTimeout(toastTimer);els.toast.textContent=msg;els.toast.classList.add('show');toastTimer=setTimeout(()=>els.toast.classList.remove('show'),ms)}
function sparkAt(xPct,yPct,char='✦'){const d=document.createElement('div');d.className='spark-pop';d.textContent=char;d.style.left=xPct+'%';d.style.top=yPct+'%';els.stage.appendChild(d);setTimeout(()=>d.remove(),820)}
function transition(kicker,title,sub,cb){setPhase('TRANSITION','TRANSITION');hideLanguage();els.transK.textContent=kicker||'';els.transT.textContent=title||'';els.transS.textContent=sub||'';els.transition.classList.add('show');log('transition',{kicker,title,sub});setTimeout(()=>{try{cb?.()}finally{setTimeout(()=>els.transition.classList.remove('show'),250)}},900)}
function dock(html){els.dock.innerHTML=html}
function tone(kind='tap'){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();const map={tap:[480,.04],bird:[880,.06],paper:[300,.045],transition:[390,.08]};const [f,d]=map[kind]||map.tap;o.frequency.value=f;o.type='sine';g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.stop(c.currentTime+d+.02);setTimeout(()=>c.close(),300)}catch{}}
const speakingTimers=new WeakMap();
function speakActor(node,mouth,duration){if(!node||!mouth||state.motion_paused||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const previous=speakingTimers.get(node);if(previous)clearTimeout(previous);node.classList.remove('speaking');void node.getBoundingClientRect();node.classList.add('speaking');speakingTimers.set(node,setTimeout(()=>node.classList.remove('speaking'),duration));}
function canNarrativeInteract(){return state.interaction_window==='FREE_EXPLORE'||state.interaction_window==='POST_STORY_FREE'} function cosmeticOnly(){return state.interaction_window==='ASSESSMENT_WAIT'||state.interaction_window==='MEDIATION_LOCKED'} function allowLargeAmbient(){return canNarrativeInteract()&&!els.stage.classList.contains('phone-scene')&&!state.motion_paused&&!matchMedia('(prefers-reduced-motion: reduce)').matches}
function interact(target,message,action){state.interaction_trace.push({t_ms:t(),target,window:state.interaction_window});log('interaction',{target,window:state.interaction_window});if(!state.motion_paused&&!matchMedia('(prefers-reduced-motion: reduce)').matches)action?.();if(cosmeticOnly())toast('教室還在動；這時不會提供新的情境資訊。');else toast(message)}
function classmateReact(node){if(state.motion_paused||!node)return;C5_EXT.gesture(API,node.id);}
let planeLaunchTimer=null;
function throwPaperPlane(force=false){if(force&&planeBusy){clearTimeout(planeLaunchTimer);els.paperPlane.getAnimations().forEach(a=>a.cancel());els.paperPlane.style.opacity='0';planeBusy=false}if(planeBusy||(!force&&!allowLargeAmbient()))return;planeBusy=true;tone('paper');
  const kid=els.peerA,paper=els.peerAPaper; if(paper){paper.animate([{transform:'translate(24px,18px) rotate(0) scale(1)'},{transform:'translate(20px,16px) rotate(-18deg) scale(.82)'},{transform:'translate(27px,18px) rotate(14deg) scale(.72)'},{transform:'translate(24px,18px) rotate(0) scale(.62)'}],{duration:1150,easing:'ease-in-out'});}
  C5_EXT.gesture(API,kid.id,'reaching');
  planeLaunchTimer=setTimeout(()=>{els.paperPlane.style.opacity='1';const a=els.paperPlane.animate([{transform:'translate(680px,450px) rotate(-22deg) scale(1)',opacity:0},{transform:'translate(760px,398px) rotate(-14deg) scale(1.3)',opacity:1,offset:.12},{transform:'translate(890px,359px) rotate(-4deg) scale(1.3)',opacity:1,offset:.38},{transform:'translate(1050px,380px) rotate(18deg) scale(1.3)',opacity:1,offset:.66},{transform:'translate(1115px,475px) rotate(66deg) scale(1.1)',opacity:1,offset:.86},{transform:'translate(1040px,585px) rotate(136deg) scale(.95)',opacity:0}],{duration:3000,easing:'cubic-bezier(.22,.61,.36,1)'});a.onfinish=()=>{els.paperPlane.style.opacity='0';planeBusy=false}},900);
  log('ambient_event',{type:'paper_plane_fold_throw_return',actor:'佳恩',window:state.interaction_window})}
function birdVisit(force=false){if(force&&birdBusy){els.birdRig.getAnimations({subtree:true}).forEach(a=>a.cancel());birdBusy=false}if(birdBusy||(!force&&!allowLargeAmbient()))return;birdBusy=true;els.birdRig.style.opacity='1';tone('bird');
  const wing=els.birdWing.animate([{transform:'rotate(0)'},{transform:'rotate(-30deg)'},{transform:'rotate(16deg)'},{transform:'rotate(-24deg)'},{transform:'rotate(0)'}],{duration:390,iterations:6,easing:'ease-in-out'});
  const a=els.birdRig.animate([{transform:'translate(-35px,235px) scale(1.3)',opacity:0},{transform:'translate(80px,257px) scale(1.4)',opacity:1,offset:.16},{transform:'translate(175px,307px) scale(1.4)',opacity:1,offset:.34},{transform:'translate(175px,307px) scale(1.4)',opacity:1,offset:.72},{transform:'translate(210px,277px) scale(1.4)',opacity:1,offset:.80},{transform:'translate(-30px,207px) scale(1.3)',opacity:0}],{duration:8200,easing:'linear'});
  setTimeout(()=>{wing.cancel();els.bird.animate([{transform:'rotate(0)'},{transform:'rotate(-7deg)'},{transform:'rotate(6deg)'},{transform:'rotate(0)'}],{duration:1000})},3100);
  a.onfinish=()=>{wing.cancel();els.birdRig.style.opacity='0';birdBusy=false;if(allowLargeAmbient())setTimeout(()=>birdVisit(),9000+Math.random()*9000)};
  log('ambient_event',{type:'bird_fly_land_pause_leave_return_scheduled',window:state.interaction_window})}
function pencilTap(force=false){if(!force&&!allowLargeAmbient())return;els.pencilArm.animate([{transform:'rotate(0)'},{transform:'rotate(7deg) translateY(-3px)'},{transform:'rotate(-4deg)'},{transform:'rotate(0)'}],{duration:820});classmateReact(els.peerB);log('ambient_event',{type:'pencil_tap',actor:'阿威',window:state.interaction_window})}
function eraserDrop(force=false){if(!force&&!allowLargeAmbient())return;els.eraser.animate([{transform:'translate(0,0) rotate(0)'},{transform:'translate(-10px,18px) rotate(35deg)',offset:.26},{transform:'translate(-20px,58px) rotate(95deg)',offset:.47},{transform:'translate(-20px,58px) rotate(95deg)',offset:.63},{transform:'translate(-4px,9px) rotate(12deg)',offset:.88},{transform:'translate(0,0) rotate(0)'}],{duration:2550,easing:'ease-in-out'});classmateReact(els.peerC);log('ambient_event',{type:'eraser_drop_pickup',actor:'小楓',window:state.interaction_window})}
function doze(force=false){if(!force&&!allowLargeAmbient())return;els.peerD.querySelector('.head').animate([{transform:'translateY(0) rotate(0)'},{transform:'translateY(4px) rotate(5deg)',offset:.2},{transform:'translateY(10px) rotate(8deg)',offset:.46},{transform:'translateY(10px) rotate(8deg)',offset:.66},{transform:'translateY(-4px) rotate(-4deg)',offset:.85},{transform:'translateY(0) rotate(0)'}],{duration:3900,easing:'ease-in-out'});log('ambient_event',{type:'homework_doze_wake',actor:'高個子同學',window:state.interaction_window})}
function scribble(force=false){if(!force&&!allowLargeAmbient())return;C5_EXT.gesture(API,'peerA','writing');log('ambient_event',{type:'scribble',actor:'佳恩',window:state.interaction_window})}
function stretch(force=false){if(!force&&!allowLargeAmbient())return;C5_EXT.gesture(API,'peerC','reaching');log('ambient_event',{type:'stretch',actor:'小楓',window:state.interaction_window})}
function runLifeEvent(){if(state.completed)return;if(allowLargeAmbient()){const events=[birdVisit,throwPaperPlane,pencilTap,eraserDrop,doze,scribble,stretch];events[Math.floor(Math.random()*events.length)]()}scheduleLifeEvents()}
function scheduleLifeEvents(){clearTimeout(lifeTimer);if(state.completed)return;lifeTimer=setTimeout(runLifeEvent,4200+Math.random()*4100)} function schedulePair(){clearTimeout(pairTimer);if(state.completed)return;pairTimer=setTimeout(()=>{if(!state.completed&&!state.motion_paused){const arr=[els.peerA,els.peerB,els.peerC,els.peerD];classmateReact(arr[Math.floor(Math.random()*arr.length)])}schedulePair()},6000+Math.random()*4200)} function primeIntroLife(){setTimeout(()=>birdVisit(),650);setTimeout(()=>scribble(),1800);setTimeout(()=>pencilTap(),3000);setTimeout(()=>throwPaperPlane(),4200);setTimeout(()=>doze(),7600);setTimeout(()=>eraserDrop(),10200);setTimeout(()=>stretch(),13200)}
function normalize(s){return safe(s).replace(/妳/g,'你').replace(/[她牠它]/g,'他').replace(/ㄧ/g,'一').replace(/\s+/g,'').replace(/我門/g,'我們').replace(/部份/g,'部分').replace(/納你/g,'那你').replace(/納我們/g,'那我們')}
function reviewReasonText(code){return({insufficient_action:'可辨識到的教師行動不足，無法可靠落入單一層級',too_brief_for_reliable_intent:'語句太短，意圖可能有多種解釋',too_brief_for_reliable_opening:'開場太短，無法可靠辨認溝通策略',novel_or_ambiguous_intent:'出現既有規則未覆蓋或可多重解釋的做法',novel_or_ambiguous_opening:'開場語意合理，但現有本機規則尚無足夠錨點',partial_or_novel_response:'已偵測部分有效線索，但不足以唯一決定層級',dismissive_or_presupposed_resolution:'語句預設事情已解決或帶有關閉對話傾向，需要人工判讀',keyword_only_or_command_only:'只命中責任／作業等關鍵字，缺少足夠關係與處理脈絡',label_without_teacher_action:'只出現標籤或判斷，沒有可辨識的教師行動',affective_support_unmapped:'偵測到情緒支持，但現行正式錨點不足以單獨決定層級',invalidating_presupposition:'語句帶有「事情應已解決」的預設，可能弱化學生經驗，需要人工判讀',written_expression_support_unmapped:'辨認到書面表達支持；續談承接另行記錄，現有層級錨點不足，保留專家重評',boundary_without_follow_through_unmapped:'已明確區分計分疑慮與作業，尚未說明具體續談安排；保留原候選供專家複核',user_disputed_interpretation:'玩家表示本機理解不符原意，首次原話保留，候選判讀待人工重評',blaming_attribution:'將目前困難直接歸因為偷懶／故意等人格或動機，需要低端警示',greeting_only_no_topic_yet:'只有寒暄，尚未出現可判讀的親師溝通切入策略'})[code]||code||'—'}
function attachDiagnostic(item,text,r){const ev=Object.values(r.evidence||{});r.development_diagnostic={disposition:r.needs_review?'MANUAL_REVIEW':'AUTO_CODED',reason_code:r.review_reason||null,reason_text:reviewReasonText(r.review_reason),matched_evidence:ev.map(x=>({code:x.code,status:x.status,reason:x.reason})),guard_hits:[...(r.interaction_features||[])],action_unit_count:r.action_units?.length||0,normalized_length:r.normalized_text?.length||0,engine_note:r.needs_review?'保留人工判讀，不以最接近的關鍵字強迫給分。':'目前規則有足夠錨點；仍屬研究原型自動編碼。'};return r}
function parentIntent(text){const t=normalize(text),hits=[];const has=(name,re)=>{if(re.test(t)){hits.push(name);return true}return false};const x={t,hits};x.availability=has('availability',/(方便|可以說|可以聊|有空|現在可以)/);x.recent=has('recent_school',/(最近|這幾天|這兩天|學校|課堂|上課|狀況|情況)/);x.event=has('competition_event',/(小組|比賽|積分|那一分|舉手|公平|不公平|那次|那件事)/);x.home=has('home_observation',/(家裡|在家|回家|媽媽|爸爸)/);x.homework=has('homework',/(作業|功課|寫完|拖延|拖)/);x.emotion=has('emotion',/(情緒|生氣|煩|不開心|不耐煩|在意|放不下|心情|感受)/);x.unheard=has('felt_unheard',/(沒聽|沒有聽|沒被聽|不理|不公平)/);x.ask=has('question',/[?？]|(嗎|呢|怎麼|如何|為什麼|有沒有|是否|什麼|哪)/);x.parentAction=has('ask_parent_action',/(你們.*(怎麼|如何|有沒有)|家裡.*(怎麼|如何|有沒有)|有跟他聊|怎麼陪|怎麼處理|以前.*怎麼)/);x.strategy=has('ask_strategy',/(平復|方法|有效|以前|過去|通常怎麼|怎麼讓他)/);x.plan=has('teacher_plan',/(明天|之後|下課|我會再|我打算|我準備|再跟他|找他談|約他|談一談)/);x.support=has('request_parent_support',/(麻煩|請.*留意|一起留意|幫忙|家裡.*留意|協助|配合|提醒)/);x.report=has('report_school_impact',/(影響.*上課|上課.*影響|作業.*拖|不配合|起口角|不想聽|不想寫)/);return x}
function parentReplyOriginal(step,teacherText){const q=parentIntent(teacherText);let text='',rule_id='';if(step==='AFTER_INITIAL'){
 if(q.event&&q.ask){text='有，他這幾天回家確實一直提那次小組比賽。尤其講到最後那一分時會比較在意。老師這邊是又看到什麼情況嗎？';rule_id='P1_EVENT_QUESTION'}
 else if(q.home||q.parentAction){text='有，我這兩天也覺得他回家比較悶一點，寫作業的速度也比平常慢。老師在學校這邊看到的是什麼狀況呢？';rule_id='P1_HOME_OBSERVATION'}
 else if(q.event){text='好，老師您說。其實子安回家也有提那次小組比賽，我有感覺他還沒有完全放下。';rule_id='P1_EVENT_ACK'}
 else if(q.recent||q.report){text='好，老師您說。是最近上課、作業，還是和同學互動有什麼狀況嗎？我這兩天也覺得他回家比較悶一點。';rule_id='P1_RECENT_OPEN'}
 else if(q.availability){text='可以，老師您說。是子安最近在學校有什麼情況嗎？';rule_id='P1_AVAILABLE'}
 else {text='好，老師您說。是子安最近有什麼事情需要一起了解嗎？';rule_id='P1_GENERAL_OPEN'}
 }else if(step==='AFTER_FOLLOW1'){
 if(q.parentAction||q.strategy){text='有，我有先讓他把那次的想法說完，也有提醒他先把每天該做的作業完成。以前他遇到輸贏比較在意時，通常先讓他講完會比較快平靜；只是這次他反覆提了好幾天。';rule_id='P2_PARENT_STRATEGY'}
 else if(q.unheard||q.event&&q.ask){text='他會一直說那一分不公平，還說當時覺得老師沒有把他的話聽完。不是一直發脾氣，但會反覆再提。';rule_id='P2_EVENT_DETAIL'}
 else if(q.homework){text='有，這兩天寫作業明顯拖比較久。本來坐下來就會開始，現在常常寫一下又停，一提到那次比賽就有點不耐煩。';rule_id='P2_HOMEWORK_DETAIL'}
 else if(q.emotion){text='他沒有一直發脾氣，比較像是悶著、反覆提那一分。有時候我們想把話題帶開，他還是會繞回去說自己覺得不公平。';rule_id='P2_EMOTION_DETAIL'}
 else if(q.report){text='這樣看起來學校和家裡看到的狀況滿一致的。家裡這兩天也覺得他做作業比較拖，一提到那次比賽就容易不耐煩。';rule_id='P2_MATCH_SCHOOL_REPORT'}
 else {text='我這邊看到的是，他這幾天會反覆提那次比賽，心情沒有到一直發脾氣，但做作業確實比平常拖。老師想先了解哪一部分，我可以再說清楚。';rule_id='P2_GENERAL_DETAIL'}
 }else{
 if(q.support){text='可以，我們家裡會一起留意。這幾天如果他又一直提那次比賽、情緒變得比較煩，或作業又拖得很明顯，我會先聽他說，也再跟老師聯絡。';rule_id='P3_SUPPORT_AGREE'}
 else if(q.plan){text='好，謝謝老師。那我今晚先不一直追問他，讓他知道老師接下來還會再聽他說；家裡這邊也會先把情緒和作業狀況留意起來。';rule_id='P3_TEACHER_PLAN'}
 else if(q.ask){text='可以，我們家裡願意配合。老師如果希望我們特別觀察哪一個狀況，可以直接跟我說，我這邊也會把看到的情形再回覆給您。';rule_id='P3_QUESTION_COLLAB'}
 else {text='好，我了解，謝謝老師跟我說。家裡這邊會繼續留意他的情緒和作業；如果又有比較明顯的變化，我再跟老師聯絡。';rule_id='P3_GENERAL_CLOSE'}
 }
 return{text,rule_id,trigger_intents:q.hits,responding_to:teacherText}}
function parentReply(step,teacherText){return C5_EXT.parentReply(step,teacherText,parentReplyOriginal)}
function resultBase(item,phase,text){return{engine_version:META.evidence_engine_version,core_version:META.core_version,item,phase,raw_text:text,normalized_text:normalize(text),action_units:safe(text).split(/[，。；;、]/).map(x=>x.trim()).filter(Boolean),evidence:{},interaction_features:[],score:null,response_status:'needs_review',needs_review:true,mixed_strategy:false,coding_certainty:'low',review_reason:'insufficient_action',interpretation_status:'formal_interpretation_uncertain',c0:null}}
function markScored(r,score,certainty='moderate'){r.score=score;r.response_status='scored';r.needs_review=false;r.review_reason=null;r.coding_certainty=certainty;r.interpretation_status='formal_evidence_coded';return r}
function guardText(t){return{short:t.length<7,dismissive:/(已經.*(說|解釋)|不是說過|就這樣|不要再|別再|不用再|乖|趕快|快點|聽話)/.test(t),labelOnly:/^(公平|輸贏|勝負|態度|情緒|作業|規則|在乎輸贏|過度在乎輸贏的態度)$/.test(t),question:/[?？]|(嗎|呢|怎麼|為什麼|哪|什麼)/.test(t),invalidating:/(不是.*(說清楚|解釋清楚|講清楚).*了嗎|有什麼好.*(煩|在意|生氣)|不要想那麼多|想太多)/.test(t),blaming:/(偷懶|就是你|你自己.*(不|沒)|都是你|不認真|故意不)/.test(t)}}
function code165Original(phase,text){
  const r=resultBase(165,phase,text),t=normalize(text),g=guardText(t);
  const precise=/(最後.*(題|一題)|那一題|那一分|分數|計分|記分|誰先舉手|先舉手|怎麼算|為什麼.*(算|給|記)|哪一組|哪個環節|哪個地方)/.test(t);
  const clarify=/(你是說|你的意思|是.*還是|哪裡|哪一部分|哪個部分|發生什麼|怎麼回事|你覺得.*怪|哪裡.*不服|哪裡.*不公平|答案.*問題)/.test(t);
  const verify=/(其他同學|問.*同學|問.*(全班|大家)|全班.*(看見|看到)|大家.*(看見|看到)|有沒有.*(看到|看見)|有人看到|誰先舉手|確認|核對|查證|比對|看.*紀錄|一起確認|重看)/.test(t);
  const listen=/(你先說|說說看|講講看|告訴老師|我想了解|我想知道|我聽|先聽|你怎麼想)/.test(t);
  const educate=/(輸贏|勝負|別太在意|接受結果|看開|不要計較|態度)/.test(t);
  const assertResolved=/(真的.*(比較快|先)|就是.*(你們|他們).*(慢|快)|分數.*沒問題|沒有要改|不用改)/.test(t)&&!verify;
  const handoff=/(家長|媽媽|爸爸|回家.*說)/.test(t),punitive=/(處罰|扣分|記警告|閉嘴|不要再吵|罵)/.test(t)&&!/不.*(處罰|扣分|罵|警告)/.test(t);
  if(verify){r.evidence['E165-VE']={code:'E165-VE',status:'affirmed',supporting_spans:[text],reason:'verifies the disputed event with an observable source'};if(precise)r.evidence['E165-DC']={code:'E165-DC',status:'affirmed',supporting_spans:[text],reason:'clarifies the concrete disputed event'};return markScored(r,4,precise?'high':'moderate')}
  if(precise&&g.question){r.evidence['E165-DC']={code:'E165-DC',status:'affirmed',supporting_spans:[text],reason:'clarifies the concrete disputed event'};return markScored(r,4,'moderate')}
  if(g.dismissive){r.review_reason='dismissive_or_presupposed_resolution';r.interaction_features.push('tone_guard:dismissive');return r}
  if(assertResolved){r.evidence['E165-UA']={code:'E165-UA',status:'affirmed',supporting_spans:[text],reason:'asserts a resolution without checking the disputed event'};return markScored(r,2)}
  if((clarify||listen)&&(g.question||listen)){r.evidence['E165-GL']={code:'E165-GL',status:'affirmed',supporting_spans:[text],reason:'general listening/clarification'};return markScored(r,3)}
  if(educate){r.evidence['E165-GE']={code:'E165-GE',status:'affirmed',supporting_spans:[text],reason:'general education/attitude focus'};return markScored(r,2)}
  if(handoff||punitive){r.evidence[handoff?'E165-PH':'E165-PU']={code:handoff?'E165-PH':'E165-PU',status:'affirmed',supporting_spans:[text],reason:handoff?'parent handoff':'punitive response'};return markScored(r,1)}
  r.review_reason=g.short?'too_brief_for_reliable_intent':'novel_or_ambiguous_intent';return r
}
function code165(phase,text){return C5_EXT.formalGuard(165,text,C5_EXT.code165(phase,text,code165Original,resultBase,markScored))}
function code166Original(phase,text,ctx={}){
  const r=resultBase(166,phase,text),t=normalize(text),g=guardText(t);
  const past=/(比賽|積分|計分|那次|那件事|上次|之前|先前|舉手|不甘願|不服|公平|那一分)/.test(t);
  const current=/(上課|作業|學習|現在|目前|今天|該做|該完成|要完成|責任|課堂|課本)/.test(t);
  const ownership=/(我會|我想|我這邊|老師會|我再|我跟你|我陪你|我來|我們)/.test(t);
  const explore=/(為什麼.*(在意|在乎|介意|放不下|生氣|煩|不服)|想.*了解.*(原因|為什麼)|想.*知道.*為什麼|跟我說.*(怎麼|為什麼)|你願意.*說)/.test(t);
  const contrastExplore=/(是.*(作業|上課|課本).*(還是|或是).*(積分|比賽|那件事)|是.*(積分|比賽|那件事).*(還是|或是).*(作業|上課|課本))/.test(t);
  const follow=/(下課.*(談|聊|處理|討論)|之後.*(談|聊|處理|討論)|再.*(談|聊|處理|確認|討論)|會再|會跟你談|會和你談|跟你談|一起.*(談|看|討論)|先.*(作業|完成).*(再|下課))/.test(t);
  const explicitBoundary=/(兩件事|分開|另外一件|不能混|是兩回事|不一樣|一邊.*一邊|先前.*(但|可是|不過).*現在|比賽.*(但|可是|不過).*作業|那件事.*會.*處理.*現在)/.test(t);
  const sequence=/(先.*(作業|完成).*(再|下課)|作業.*(下課|之後).*(談|處理|聊|討論)|情緒.*下課.*(處理|談|討論)|先.*(今天|現在).*(做|完成).*(下課|之後))/.test(t);
  const harsh=/(處罰|扣分|記過|警告|威脅|閉嘴|不要鬧)/.test(t)&&!/不.*(處罰|扣分|警告)/.test(t);
  const invalidating=g.invalidating, blaming=g.blaming;
  const commandOnly=current&&!past&&!explore&&!contrastExplore&&!follow&&!ownership&&(g.short||g.dismissive);
  const priorContext=!!ctx.two_sided||!!ctx.post_reveal;
  if(ownership)r.evidence['E166-TO']={code:'E166-TO',status:'affirmed',supporting_spans:[text],reason:'teacher retains ownership'};
  if(current)r.evidence['E166-CR']={code:'E166-CR',status:'affirmed',supporting_spans:[text],reason:'current responsibility/situation acknowledged'};
  if(past)r.evidence['E166-PA']={code:'E166-PA',status:'affirmed',supporting_spans:[text],reason:'prior issue acknowledged'}; else if(priorContext&&(follow||sequence||/心情|感受|不舒服|在意/.test(t)))r.evidence['E166-PA']={code:'E166-PA',status:'context_resolved',supporting_spans:[ctx.post_reveal?'L3-166 immediate context':'L2-166-R prompt context'],reason:'prior issue is recoverable from the immediately preceding shared context'};
  if(follow)r.evidence['E166-PC']={code:'E166-PC',status:'affirmed',supporting_spans:[text],reason:'later follow-up keeps the prior issue open'};
  if((past&&current&&(explicitBoundary||sequence))||(priorContext&&current&&(sequence||follow)))r.evidence['E166-BI']={code:'E166-BI',status:explicitBoundary?'affirmed':'context_resolved',supporting_spans:[explicitBoundary?text:'immediate context + sequenced reply'],reason:explicitBoundary?'explicitly distinguishes prior issue from current responsibility':'distinguishes the two demands by sequencing them in context'};
  if(explore||contrastExplore)r.evidence['E166-ER']={code:'E166-ER',status:'affirmed',supporting_spans:[text],reason:contrastExplore?'contrasts current avoidance with the earlier event':'explores why the earlier event remains salient'};
  if(harsh||blaming){r.evidence={};r.interaction_features.push(blaming?'quality_guard:blaming_attribution':'quality_guard:harsh');r.review_reason=blaming?'blaming_attribution':'harsh_or_punitive';return markScored(r,1,'moderate')}
  if(invalidating){r.evidence={};r.interaction_features.push('tone_guard:invalidating');r.review_reason='invalidating_presupposition';return r}
  if(commandOnly){r.score=null;r.evidence={};r.review_reason='keyword_only_or_command_only';r.interaction_features.push('quality_guard:command_only');return r}
  if(g.labelOnly){r.evidence={};r.review_reason='label_without_teacher_action';return r}
  if(explicitBoundary&&current&&(past||priorContext)&&follow)return markScored(r,4,'high');
  if(r.evidence['E166-BI']&&r.evidence['E166-CR']&&(r.evidence['E166-PA']||r.evidence['E166-PC']))return markScored(r,3,'moderate');
  if(contrastExplore||explore||(ownership&&past))return markScored(r,3);
  if(current&&!past&&!explore&&!contrastExplore&&t.length>=10)return markScored(r,2);
  if(/(在乎你的感受|理解你的感受|我知道你很在意|我知道你很煩|聽得出來你很在意)/.test(t)){r.review_reason='affective_support_unmapped';r.interaction_features.push('signal:affective_support');return r}
  r.review_reason='partial_or_novel_response';return r
}
function code166(phase,text,ctx={}){return C5_EXT.formalGuard(166,text,C5_EXT.code166(phase,text,ctx,code166Original,resultBase,markScored))}
function code167Original(phase,text){
  const r=resultBase(167,phase,text),t=normalize(text),g=guardText(t);
  const event=/(小組|比賽|積分|計分|那次|那件事|那一分)/.test(t),recent=/(最近|這幾天|上課|作業|學習|課堂|學校|沒有交|不配合|拖延|狀況|情況)/.test(t),contact=/(想跟您說|想跟您談|想了解|想問|聯絡|跟您說明|聊一下|想聊|找您聊|跟您聊|也正想.*聊|正想.*聊)/.test(t),family=/(在家|回家|家裡|情緒|有沒有提|有提到|有注意到|有觀察到|是否)/.test(t),record=/(紀錄|記錄|資料|學習單)/.test(t),blame=/(都是你們|家裡要|請你們管|管好|你們沒有)/.test(t);
  if(blame){r.evidence['E167-BL']={code:'E167-BL',status:'affirmed',supporting_spans:[text],reason:'blame-first opening'};return markScored(r,1)}
  if(record&&!recent&&!event){r.evidence['E167-RF']={code:'E167-RF',status:'affirmed',supporting_spans:[text],reason:'record-first opening'};return markScored(r,1)}
  if(event&&recent&&contact){r.evidence['E167-FC']={code:'E167-FC',status:'affirmed',supporting_spans:[text],reason:'contextual opening connects event and recent change'};return markScored(r,4,'high')}
  if(recent&&contact){r.evidence['E167-RC']={code:'E167-RC',status:'affirmed',supporting_spans:[text],reason:'recent school situation introduced collaboratively'};return markScored(r,3)}
  if(family&&(event||recent)&&contact){r.evidence['E167-RC']={code:'E167-RC',status:'affirmed',supporting_spans:[text],reason:'invites family observation around a relevant concern'};return markScored(r,3)}
  if(event&&contact){r.evidence['E167-SF']={code:'E167-SF',status:'affirmed',supporting_spans:[text],reason:'single event fragment opening'};return markScored(r,2)}
  if(/^(家長|媽媽|爸爸)?(您|你)?好[!！。]?$/.test(t)){r.interaction_features.push('signal:greeting_only');r.review_reason='greeting_only_no_topic_yet';return r}
  r.review_reason=g.short?'too_brief_for_reliable_opening':'novel_or_ambiguous_opening';return r
}
function code167(phase,text){return C5_EXT.formalGuard(167,text,C5_EXT.code167(phase,text,code167Original,resultBase,markScored))}
function code(item,phase,text,ctx={}){const r=item===165?code165(phase,text):item===166?code166(phase,text,ctx):code167(phase,text);return attachDiagnostic(item,text,r)}
function recordResponse(item,phase,slot,promptId,promptVersion,text,result){const rt=Math.round(now()-phaseStarted);state.responses.push({item:String(item),phase,slot,prompt_id:promptId,prompt_version:promptVersion,input_mode:'keyboard_text',submitted_t_ms:t(),response_time_ms:rt,raw_text:text,normalized_text:result.normalized_text,evidence:result.evidence,interaction_features:result.interaction_features,score:result.score,response_status:result.response_status,needs_review:result.needs_review,review_reason:result.review_reason,coding_certainty:result.coding_certainty,rubric_mapping:result.rubric_mapping||null,development_diagnostic:result.development_diagnostic||attachDiagnostic(item,text,result).development_diagnostic,engine_version:META.evidence_engine_version,core_version:META.core_version});state.items[item].records?.push({stage:phase,text,result});if((phase==='INITIAL'||phase==='POST')&&!state.items[item].formal[phase])state.items[item].formal[phase]=result;Object.values(result.evidence).forEach(ev=>{if(!state.items[item].support_evidence?.[ev.code]){state.items[item].support_evidence[ev.code]={...ev,origin:phase};state.items[item].evidence_first_observed_stage[ev.code]=phase}});log('response_submitted',{item,slot,response_time_ms:rt,score:result.score,codes:Object.keys(result.evidence),needs_review:result.needs_review,review_reason:result.review_reason,input_mode:'keyboard_text'});return result}
function responseUI({title,sub='',badge='',placeholder='輸入你真的會說出口的話…',button='說出去',onSend}){dock(`${badge?`<div class="support-badge">${esc(badge)}</div>`:''}<div class="dock-head"><div><div class="dock-title">${esc(title)}</div>${sub?`<div class="dock-sub">${esc(sub)}</div>`:''}</div></div><textarea id="answerBox" maxlength="500" placeholder="${esc(placeholder)}"></textarea><div class="input-meta"><small><span id="charCount">0</span> / 500</small><small id="voiceHint">可直接打字；支援的瀏覽器也可使用語音輸入</small></div><div class="input-actions"><button class="btn primary" id="sendAnswer">${esc(button)}</button><button class="btn voice" id="voiceAnswer" type="button">🎙 語音輸入</button></div>`);const box=$('#answerBox'),count=$('#charCount'),voice=$('#voiceAnswer');box.addEventListener('input',()=>count.textContent=box.value.length);setTimeout(()=>box.focus(),80);
  const submit=()=>{const v=box.value;if(!v.trim()){toast('先寫下你想說的話。');return}const send=$('#sendAnswer');send.disabled=true;voice.disabled=true;box.disabled=true;els.dock.querySelectorAll('button').forEach(b=>b.disabled=true);tone('tap');presentUserUtterance(v);setTimeout(()=>onSend(v),els.stage.classList.contains('phone-scene')?480:1650)};$('#sendAnswer').onclick=submit;box.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&!box.disabled){e.preventDefault();submit()}});
  voice.onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('這個瀏覽器目前沒有可用的語音辨識；請改用文字輸入。',2600);return}try{const rec=new SR();rec.lang='zh-TW';rec.interimResults=true;rec.continuous=false;voice.classList.add('listening');voice.textContent='● 聆聽中';state.parent_interaction.voice_control_uses+=(els.stage.classList.contains('phone-scene')?1:0);let finalText='';rec.onresult=e=>{let temp='';for(let i=e.resultIndex;i<e.results.length;i++){const tx=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=tx;else temp+=tx}box.value=(finalText||temp).trim();count.textContent=box.value.length};rec.onerror=()=>toast('語音辨識沒有成功，原本輸入內容不會消失。',2200);rec.onend=()=>{voice.classList.remove('listening');voice.textContent='🎙 語音輸入'};rec.start()}catch{toast('目前無法啟動語音輸入。',2200)}}}
function confirmOrProceed(item,phase,slot,promptId,promptVersion,text,result,onDone){recordResponse(item,phase,slot,promptId,promptVersion,text,result);if(result.needs_review){onDone(result);return}if(result.coding_certainty!=='high'){setTimeout(()=>onDone(result),380);return}const summary=item===165?'我理解你是在確認具體爭議或準備查證事件。':item===166?'我理解你有把先前事件和目前課堂責任分開處理。':'我理解你同時交代了事件脈絡與最近的學校變化。';dock(`<div class="dock-title">確認一下你的意思</div><div class="dock-sub">這裡只核對本機判讀，不顯示高低或對錯。</div><div style="margin-top:10px;padding:11px 12px;border-radius:13px;background:#f2ede5;border:1px solid #dfd3c4">${esc(summary)}</div><div class="actions"><button class="btn primary" id="confirmYes">是，我是這個意思</button><button class="btn secondary" id="confirmRewrite">不是，我重說一次</button></div>`);$('#confirmYes').onclick=()=>{result.user_confirmed=true;state.responses.at(-1).user_confirmed=true;onDone(result)};$('#confirmRewrite').onclick=()=>{result.user_confirmed=false;result.candidate_score=result.score;result.score=null;result.needs_review=true;result.response_status='needs_review';result.review_reason='user_disputed_interpretation';result.coding_certainty='low';result.interpretation_status='formal_interpretation_uncertain';result.interaction_features.push('user_disputed_interpretation');attachDiagnostic(item,text,result);Object.assign(state.responses.at(-1),{user_confirmed:false,candidate_score:result.candidate_score,score:null,needs_review:true,response_status:result.response_status,review_reason:result.review_reason,coding_certainty:'low',development_diagnostic:result.development_diagnostic});log('interpretation_disputed',{item,phase,raw_text:text,candidate_score:result.candidate_score});responseUI({title:item===167?'你會怎麼開始這通電話？':'你現在會怎麼說？',sub:'原回答已保留，這次是重新表達。',onSend:v=>{const r=code(item,phase,v);confirmOrProceed(item,phase,slot,promptId,promptVersion,v,r,onDone)}})}}
function contextualReply166(text,context={}){
 clearNarration();
 const memory=state.student_dialogue166 ||= {version:'STUDENT-CONTEXT-20261004.13',history:[]};
 const resolution=C5_EXT.resolve166(text,{...context,history:memory.history});
 const record=state.items[166].records.at(-1);resolution.sourceId=sessionId+'-D166'+(memory.history.length+1);resolution.recordStage=record?.stage||null;resolution.t_ms=t();memory.history.push(resolution);log('student_reply_resolved',{item:166,...resolution});C5_GUIDANCE.render(API,resolution,true);return resolution.text;
}
function supportPrompt(item,level,prompt,ctx,onDone){state.items[item].support_path.push(`${level}-${item}${level==='L2'&&item===166?'-R':''}`);setPhase(`${item}_${level}`,'MEDIATION_LOCKED');
  const fallbackLine=item===165?(level==='L1'?'我就是覺得我們也答對了，怎麼沒有分。': '他們是比較快啦，可是我們也有答對啊。'):(level==='L1'?'可是我只要想到那天就很煩，現在看到作業也不想碰。':'所以你是要我先把今天該做的做完，但那次比賽的事你還會再跟我談，對嗎？');const studentLine=item===166?contextualReply166(state.items[item].records.at(-1)?.text||'',{level}):C5_EXT.studentReply(item,state.items[item].records.at(-1)?.text||'',fallbackLine,{level});showStudent(studentLine,item===165);
  const progress=item===166?state.student_dialogue166.history.at(-1)?.progress:null;
  const micro=state.student_dialogue166?.history.at(-1)?.guidance?.microAction;const actionLabel=({circleFractions:'他已圈出分數',readTask:'他已讀過題目',drawOutline:'他已畫了兩條'})[micro]||'他已拿起筆';
  const progressingPrompt=progress?.helpAccepted&&level==='L1'?'他願意讓你陪同了。你會怎麼接著跟他談？':progress?.workStarted&&level==='L2'?actionLabel+'。你會怎麼把那天的事與現在的學習說清楚，讓安排接下去？':prompt;
  const promptVersion=progressingPrompt!==prompt?`MED-${item}-${level}-PROGRESS-20261004.13`:`MED-${item}-${level}-CORE13-20260922`;
  log('followup_prompt_presented',{item,level,text:progressingPrompt,promptVersion,progressSource:progress?state.student_dialogue166.history.at(-1).sourceId:null});
  setTimeout(()=>responseUI({title:progressingPrompt,sub:'直接回應子安即可；前面的回答會完整保留。',badge:`引導 ${level}`,button:'說出去',onSend:text=>{const r=code(item,level,text,ctx);recordResponse(item,level,level.toLowerCase(),`${level}-${item}${level==='L2'&&item===166?'-R':''}`,promptVersion,text,r);onDone(r)}}),350)}
function standardizedInfo(item,text,next,options={}){state.items[item].support_path.push(`L3-${item}`);setPhase(`${item}_L3`,'MEDIATION_LOCKED',item===165?34:71);if(options.retrospective)narration(text,'前幾天・子安先前提過');else showStudent(text,true);log('mediation_presented',{presentation_frame:options.retrospective?'SCN166-RETROSPECTIVE-20261004.13':'currentStudentSpeech',item,level:'L3',id:`L3-${item}`,text,version:item===166?'SCN166-COMMON-INFO-20261004.9':'SCN165-COMMON-INFO-20261004.8'});dock(`<div class="support-badge">新的情境資訊</div><div class="dock-title">聽到這些後，你會怎麼回應？</div><div class="dock-sub">這是所有受測者都會看到的同一段新資訊；前面的原始回答不會被覆蓋。</div><div class="actions"><button class="btn primary" id="postGo">回應子安</button></div>`);$('#postGo').onclick=next}
function intro(){setPhase('INTRO','FREE_EXPLORE',5);els.stage.className='stage';hideParent();hideLanguage();els.sceneTag.textContent='星期二 上午';dock(`<div class="dock-head"><div><div class="dock-title">小組競賽剛結束</div><div class="dock-sub">你是五年三班導師。先看看教室，也可以點點人物或物件；準備好再進入情境。</div></div></div><div class="mini-row" style="margin-top:11px"><button class="chip" id="lookRoom">看看教室</button><button class="chip" id="pokeBag">碰碰書包</button><button class="chip" id="pokePlant">碰碰盆栽</button><button class="chip" id="pokeCurtain">拉一下窗簾</button><button class="chip" id="pokeShelf">碰碰書櫃</button></div><div class="actions"><button class="btn primary" id="beginScene">開始情境</button></div><div class="footnote">環境互動只增加臨場感；正式作答階段不會因點擊而新增評量資訊。</div>`);$('#lookRoom').onclick=()=>{if(!state.first_look.includes('room'))state.first_look.push('room');log('explore',{target:'room'});toast('窗簾輕晃，有人寫字、有人發呆，窗邊偶爾會有小鳥來。')};$('#pokeBag').onclick=()=>$('#bagHotspot').dispatchEvent(new Event('click'));$('#pokePlant').onclick=()=>$('#plantHotspot').dispatchEvent(new Event('click'));$('#pokeCurtain').onclick=()=>$('#curtainHotspot').dispatchEvent(new Event('click'));$('#pokeShelf').onclick=()=>$('#bookcaseHotspot').dispatchEvent(new Event('click'));$('#beginScene').onclick=begin165;log('session_start',{session_id:sessionId,app_version:META.app_version});primeIntroLife();scheduleLifeEvents();schedulePair()}
function begin165(){transition('第一段','小組競賽剛結束','教室裡的氣氛還沒有完全散去。',()=>{els.stage.classList.add('zian-arrived');els.zian.classList.add('walking');setTimeout(()=>els.zian.classList.remove('walking'),950);setPhase('165_STIMULUS','LOCKED_STIMULUS_DELIVERY',12);els.sceneTag.textContent='星期二 上午｜情境一';narration('最後一題兩組都答對；第二組先舉手，依規則得兩分。第一組的子安看了黑板，走到你身邊。');setTimeout(()=>{setPhase('165_INITIAL','ASSESSMENT_WAIT',16);showStudent('老師，我還是覺得剛剛那題沒得分很怪。',true);responseUI({title:'你會先怎麼回應子安？',sub:'先留下你自己的第一個反應，不給提示。',onSend:text=>{const r=attachDiagnostic(165,text,code165('INITIAL',text));confirmOrProceed(165,'INITIAL','initial','INITIAL-165','SCN-165-INITIAL-20261004.8',text,r,after165Initial)}})},900)})}
function after165Initial(r){if(r.score===4){state.items[165].target_pattern_first_met_stage='INITIAL';return standardized165()}supportPrompt(165,'L1','你會怎麼接著問，才更知道他在意的是什麼？',{},r1=>{if(r1.score===4){state.items[165].target_pattern_first_met_stage='L1';return standardized165()}supportPrompt(165,'L2','你會怎麼回應，才能把他在意的地方問清楚？',{},r2=>{if(r2.score===4)state.items[165].target_pattern_first_met_stage='L2';standardized165()})})}
function standardized165(){
 const last=state.items[165].records.at(-1),reply=last?.stage==='L2'?C5_EXT.studentReply(165,last.text,null):null;
 if(reply){setPhase('165_ACK','MEDIATION_LOCKED');showStudent(reply,true);dock('<div class="dock-title">子安接著你的話說</div><div class="dock-sub">他停了一下，又補充自己的想法。</div>');log('student_reply_resolved',{item:165,respondingTo:last.text,text:reply,recordStage:last.stage,recordIndex:state.items[165].records.length-1,sourceId:sessionId+'-165-'+last.stage,sourceVersion:'STUDENT-CONTEXT-20261004.11'});setTimeout(present165Information,2400);return;}
 present165Information();
}
function present165Information(){standardizedInfo(165,'我不是一定要你把分數改掉啦。我知道他們比較快，可是我們也答對了。怎麼好像都不算？',()=>{setPhase('165_POST','ASSESSMENT_WAIT',39);responseUI({title:'聽到這些後，你會怎麼回應？',sub:'請直接輸入你現在真的會對子安說的話。',onSend:text=>{const r=attachDiagnostic(165,text,code165('POST',text));confirmOrProceed(165,'POST','post','POST-165','SCN-165-POST-20261004.8',text,r,after165Post)}})})}
function after165Post(){narration('子安知道第二組先舉手。他仍在意的是：自己那組也答對、努力寫了理由，卻沒有競賽得分。','情境一');setPhase('POST_REVEAL_165','POST_STORY_FREE',44);showStudent('我不是一定要你把分數改給我們。我們討論很久，也把理由寫好了。可是沒得分，就覺得好像白做了。',true);log('full_event_reveal_after_post',{item:165,text:els.studentText.textContent});dock('<div class="dock-title">子安把疑問說完整了</div><div class="dock-sub">你留意到後面同學已經收好小白板，正等著下一個安排。</div><div class="actions"><button class="btn primary" id="recoverBegin">接著看看全班</button></div>');$('#recoverBegin').onclick=()=>C5_EXT.beginM01(API)}
function begin166(){els.stage.classList.remove('zian-arrived');els.stage.classList.add('behavior-scene');setPhase('166_STIMULUS','LOCKED_STIMULUS_DELIVERY',52);els.sceneTag.textContent='同一週 · 數日後｜情境二';narration('星期四，班上正在整理數學學習單。你走到子安旁邊，他的理由那格還空著，筆放在一邊。');setTimeout(()=>{showStudent('我現在看到那個積分就很煩……而且我真的不想寫。');setPhase('166_INITIAL','ASSESSMENT_WAIT',56);responseUI({title:'你先怎麼跟子安談？',sub:'先留下你自己的第一個反應。',onSend:text=>{const r=attachDiagnostic(166,text,code166('INITIAL',text));confirmOrProceed(166,'INITIAL','initial','INITIAL-166','SCN-166-INITIAL-20261004.8',text,r,after166Initial)}})},950)}
function after166Initial(r){if(r.score===4){state.items[166].target_pattern_first_met_stage='INITIAL';return standardized166()}supportPrompt(166,'L1','你會怎麼接住他現在的情緒，同時繼續談下去？',{},r1=>{if(r1.score===4){state.items[166].target_pattern_first_met_stage='L1';return standardized166()}supportPrompt(166,'L2','你會怎麼把「之前那件事」和「現在課堂上該做的事」一起說清楚？',{two_sided:true},r2=>{if(r2.score===4)state.items[166].target_pattern_first_met_stage='L2';standardized166()})})}
function standardized166(){
 const records=state.items[166].records,last=records.at(-1)?.text||'';
 const ack=contextualReply166(last,{level:records.at(-1)?.stage});
 setPhase('166_ACK','LOCKED_STIMULUS_DELIVERY',70);showStudent(ack,true);
 log('contextual_acknowledgement',{item:166,responding_to:last,text:ack,sourceVersion:'SCN166-ACK-20261004.13'});
 const contextNote=state.student_dialogue166.history.at(-1).guidance?.attention==='worksheet'?'他把注意力轉到學習單。你也想起這幾天尚待處理的情況。':'你也想起這幾天，除了那次競賽，課堂上還有哪些情況需要了解。';
 dock('<div class="dock-title">子安回應了你</div><div class="dock-sub">'+contextNote+'</div><div class="actions"><button class="btn primary" id="hearMore166">看看這幾天的背景</button></div>');
 $('#hearMore166').onclick=()=>{
  narration('你想起子安前幾天說過的情況。當前的陪同與學習安排繼續保留。','這幾天的背景');
  standardizedInfo(166,'這幾天想到那一題就很煩，老師在講什麼我也沒在聽。學習單還有好幾張沒寫。',()=>{setPhase('166_POST','ASSESSMENT_WAIT',76);responseUI({title:'聽到這些後，你會怎麼回應？',sub:'請直接輸入你現在真的會說出口的話。',onSend:text=>{const r=attachDiagnostic(166,text,code166('POST',text,{post_reveal:true}));confirmOrProceed(166,'POST','post','POST-166','SCN-166-POST-20261004.13',text,r,after166Post)}})},{retrospective:true});
 };
}

function after166Post(){C5_EXT.teachingBridge(API)}
function beginColleague(){
  els.stage.classList.remove('behavior-scene');els.stage.classList.add('colleague-scene');setPhase('COLLEAGUE_BRIDGE','POST_STORY_FREE',81);els.sceneTag.textContent='下課時間｜科任老師';narration('下課後，你在走廊遇到自然科老師，她想交換子安這兩天的課堂觀察。','情境補充');
  setTimeout(()=>{if(state.phase==='COLLEAGUE_BRIDGE'&&!state.colleague_interaction?.turns)showColleague('跟你說一下，子安這兩天在我課堂上也比較容易跟旁邊同學起口角，提醒他的時候有點不耐煩。我想說你這邊是不是也有注意到。')},420);
  dock(`<div class="dock-title">你會怎麼回應科任老師？</div><div class="dock-sub">這一段是校內協作情境，不納入 165–167 正式計分；你的選擇會保留在歷程紀錄。</div><div class="choice-grid" id="colleagueChoices"><button class="choice-card" data-c="time">先問發生時間與情況</button><button class="choice-card" data-c="compare">比對兩邊觀察</button><button class="choice-card" data-c="watch">這幾天一起留意</button><button class="choice-card" data-c="note">先知道即可</button></div>`);
  $('#colleagueChoices').querySelectorAll('button').forEach(b=>b.onclick=()=>colleagueChoice(b.dataset.c,b.textContent));C5_EXT.extendColleague(API);
}
function colleagueChoice(choice,label){
  state.colleague_interaction={choice,label,t_ms:t()};log('colleague_interaction',{choice,label,event_type:'narrative_interaction'});
  const teacherLine={time:'是發生在哪一節？當時前後大概怎麼回事？',compare:'我這邊也有看到他最近比較容易被那次比賽影響，我們對一下兩邊看到的情況。',watch:'我這邊會再跟他談，這幾天也麻煩你一起幫我留意他在自然課的狀況。',note:'好，我先記下來，謝謝你跟我說。'}[choice];
  showTeacher(teacherLine);
  setTimeout(()=>{showColleague(choice==='note'?'好，如果我這邊又看到比較明顯的狀況，再跟你說。':'好，我把我這邊看到的時間點和情況整理一下，也會繼續留意。');dock(`<div class="dock-title">校內觀察已補進來</div><div class="dock-sub">你現在多了一個不同課堂的觀察來源，接下來進入放學後的親師溝通。</div><div class="actions"><button class="btn primary" id="toParentCall">繼續到放學後</button></div>`);$('#toParentCall').onclick=()=>transition('放學後','家長來電','你接起電話，準備交換彼此看到的狀況。',begin167)},900);
}
function begin167(){els.stage.classList.remove('behavior-scene','colleague-scene');els.stage.classList.add('after-school','phone-scene');hideLanguage();if(els.callHistory)els.callHistory.innerHTML='';setPhase('167_PREINITIAL','FREE_EXPLORE',85);els.sceneTag.textContent='放學後｜親師溝通';narration('放學後，子安家長打來電話。你接起電話，準備把學校這幾天的觀察和家長交換。','情境三');showParent('老師您好，現在方便說話嗎？我想跟您聊一下子安這幾天的狀況。',0,{rule_id:'P0_OPENING_QUESTION_WITH_TOPIC'});dock(`<div class="dock-title">電話接通了</div><div class="dock-sub">家長先確認你現在是否方便。請用你平常真的會採用的方式開始這通電話。</div><div class="actions"><button class="btn primary" id="startCall">回應家長</button></div>`);$('#startCall').onclick=()=>{setPhase('167_INITIAL','ASSESSMENT_WAIT',88);responseUI({title:'你會怎麼開始這通電話？',sub:'把你真的會對家長說的第一段話說出去。',onSend:text=>{const r=attachDiagnostic(167,text,code167('INITIAL',text));confirmOrProceed(167,'INITIAL','initial','INITIAL-167','SCN-167-INITIAL-20260922-V6',text,r,()=>parentFollow1(text))}})}}
function parentFollow1(teacherText){setPhase('167_FOLLOW1','POST_STORY_FREE',92);const pr=parentReply('AFTER_INITIAL',teacherText);showParent(pr.text,1,pr);responseUI({title:'你接著會怎麼說？',sub:'家長會依你剛才說的內容回應；這一段不再計第二個 167 分數，只保留為親師溝通歷程。',button:'說出去',onSend:text=>{const rt=Math.round(now()-phaseStarted);state.items[167].communication_trace.push({step:'FOLLOW1',raw:text,submitted_t_ms:t(),response_time_ms:rt,parent_rule_before:pr.rule_id});log('communication_trace',{step:'FOLLOW1',length:text.length,response_time_ms:rt,parent_rule_before:pr.rule_id,input_mode:'keyboard_text'});setTimeout(()=>parentFollow2(text),300)}})}
function parentFollow2(teacherText){setPhase('167_FOLLOW2','POST_STORY_FREE',96);const pr=parentReply('AFTER_FOLLOW1',teacherText);showParent(pr.text,2,pr);responseUI({title:'聽到家長這樣說，你接下來會怎麼回應？',sub:'你可以追問、提出處理方式，或和家長協調後續；家長下一句會依你的內容接續。',button:'說出去',onSend:text=>{const rt=Math.round(now()-phaseStarted);state.items[167].communication_trace.push({step:'FOLLOW2',raw:text,submitted_t_ms:t(),response_time_ms:rt,parent_rule_before:pr.rule_id});log('communication_trace',{step:'FOLLOW2',length:text.length,response_time_ms:rt,parent_rule_before:pr.rule_id,input_mode:'keyboard_text'});setTimeout(()=>parentClosing(text),320)}})}
function parentClosing(teacherText){const pr=parentReply('CLOSING',teacherText);showParent(pr.text,3,pr);dock('<div class="dock-title">你可以繼續談，也可以結束通話</div><div class="dock-sub">家長回應已留下來。如果還有想確認的事，可以接著說。</div><div class="actions"><button class="btn primary" id="anotherCallTurn">繼續談</button><button class="btn secondary" id="endCall">結束通話</button></div>');$('#endCall').onclick=finish;$('#anotherCallTurn').onclick=()=>{setPhase('167_EXTENSION','POST_STORY_FREE',97);responseUI({title:'你還想和家長確認什麼？',sub:'繼續交換觀察，或把後續安排說清楚。',onSend:text=>{state.items[167].communication_trace.push({step:'EXTENSION',raw:text,submitted_t_ms:t(),parent_rule_before:pr.rule_id});log('communication_trace',{step:'EXTENSION',raw:text,parent_rule_before:pr.rule_id});parentClosing(text)}})}}

function scoreText(v){return v==null?'待檢核':v+'/4（示範）'}
function scoreCell(item){const rec=state.items[item],i=rec.formal.INITIAL?.score,p=rec.formal.POST?.score;const reason=item===165?'是否聚焦具體爭議／查證事件':item===166?'是否區分先前事件與目前責任':'第一次親師溝通的切入方式';const ir=rec.formal.INITIAL?.needs_review,pr=rec.formal.POST?.needs_review;return `<div class="result-card"><h3>${item}｜${item===165?'小組競賽爭議':item===166?'後續上課與作業狀況':'與家長開始溝通'}</h3><div class="score-row"><span class="score ${ir?'review-score':''}">${scoreText(i)}</span>${ir?'<span class="dev-badge">需人工判讀</span>':''}${item!==167?`<span class="arrow">→</span><span class="score ${pr?'review-score':''}">${scoreText(p)}</span>${pr?'<span class="dev-badge">需人工判讀</span>':''}`:''}</div><div class="reason">${reason}</div>${C5_EXT.responseEvidence(API,rec.formal.INITIAL,'首次回應')}${item!==167?C5_EXT.responseEvidence(API,rec.formal.POST,'共同新資訊後'):''}${rec.records.some(row=>!['INITIAL','POST'].includes(row.stage))?'<details class="round-scores"><summary>查看追問回合的判讀（分開列出）</summary>'+rec.records.filter(row=>!['INITIAL','POST'].includes(row.stage)).map(row=>'<article><small>'+esc(row.stage)+' · '+scoreText(row.result.score)+'</small>'+C5_EXT.responseEvidence(API,row.result,'這一回合')+'</article>').join('')+'</details>':''}<div class="trace">${['INITIAL',...(rec.support_path||[]),...(item!==167?['POST']:[])].map(x=>`<span>${esc(x)}</span>`).join('')}</div></div>`}
function devAuditItem(item){const rec=state.items[item];return (rec.records||[]).map(row=>{const x=row.result||{},ev=Object.values(x.evidence||{}),d=x.development_diagnostic||{};return `<div class="audit-item"><div class="audit-head"><span class="audit-stage">${item} · ${esc(row.stage)}</span><span class="audit-status ${x.needs_review?'review':''}">${x.needs_review?'待人工檢核':'本機已編碼 '+(x.score==null?'—':x.score+'/4')}</span></div><div class="audit-raw">「${esc(row.text)}」</div><div class="audit-grid"><span><b>certainty</b> ${esc(x.coding_certainty||'—')}</span><span><b>reason</b> ${esc(x.review_reason||'—')}</span><span><b>normalized</b> ${esc(x.normalized_text||'—')}</span><span><b>units</b> ${x.action_units?.length||0}</span></div><div class="audit-codes">${ev.length?ev.map(e=>`<span class="audit-code">${esc(e.code)} · ${esc(e.status)}</span>`).join(''):'<span class="audit-code">no formal evidence</span>'}</div><div class="audit-note">${esc(d.reason_text||reviewReasonText(x.review_reason))}${(x.interaction_features||[]).length?'｜guard: '+esc(x.interaction_features.join(', ')):''}</div></div>`}).join('')}
function parentAudit(){const h=state.parent_interaction.history||[];return h.map(x=>`<div class="parent-rule-row"><b>${x.role==='teacher'?'導師':'子安家長'}</b>：${esc(x.text)}${x.role==='parent'&&x.rule_id?`<br><small>local reply rule: ${esc(x.rule_id)}${x.trigger_intents?.length?' · matched: '+esc(x.trigger_intents.join(', ')):''}</small>`:''}</div>`).join('')}
function finish(){setPhase('COMPLETE','POST_STORY_FREE',100);state.completed=true;C5_SCENES.stop(API);clearTimeout(lifeTimer);clearTimeout(pairTimer);birdBusy=false;planeBusy=false;state.end=Date.now();log('session_complete',{target_evidence_emergence:state.items[165].target_pattern_first_met_stage,support_path:state.items[165].support_path});hideLanguage();hideParent();els.stage.classList.remove('phone-scene');narration('通話結束。你把孩子、科任老師與家長說的話分開記下來，留待接下來核對與追蹤。','今天先到這裡');C5_EXT.gesture(API,'teacher','writing');els.dock.classList.add('hidden');const r=$('#results');r.classList.remove('hidden');r.innerHTML=`<div class="dock-title" style="font-size:24px">這次的判斷歷程</div><div class="dock-sub">三題的首次回應與新資訊後回應分開保存。這些是原版暫定規則的示範參照，並非正式能力分數。</div><div class="result-grid">${scoreCell(165)}${scoreCell(166)}${scoreCell(167)}</div><details class="dev-audit"><summary>開發檢核資訊｜逐次作答、evidence、guard 與待檢核原因</summary><div class="dev-audit-body">${devAuditItem(165)}${devAuditItem(166)}${devAuditItem(167)}</div></details><details class="dev-audit"><summary>親師對話規則追蹤｜確認家長有沒有接到你上一句</summary><div class="dev-audit-body">${parentAudit()}</div></details><div class="result-note">「待檢核」在此版本是實際的不確定狀態：本機規則寧可保留人工判讀，也不會只因命中單一關鍵字硬給分。開發檢核區會把原句、正規化文字、evidence、certainty、reason code 與 guard 全部攤開。4 分與 1 分受原題高低端策略錨定；中間層級與自動判讀仍需專家審查、人工重評與實證驗證。本頁不計算三題總分。167 僅計 INITIAL；後續對話只作溝通歷程與上下文回應測試。</div><div class="actions"><button class="btn primary" id="exportResult">匯出 JSON</button><button class="btn secondary" id="restartResult">重新體驗</button></div>`;r.querySelector('.dev-audit').insertAdjacentHTML('beforebegin',C5_EXT.resultPanel(API)+C5_GUIDANCE.resultPanel(API));$('#exportResult').onclick=exportJson;$('#restartResult').onclick=()=>location.reload();els.sceneTag.textContent='放學後｜通話結束';els.stateTag.textContent='已完成';r.setAttribute('tabindex','-1');r.focus({preventScroll:true});setTimeout(()=>r.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}),250)}
function deviceContext(){const w=innerWidth,h=innerHeight;return{layout_mode:w<=720?'mobile':w<=1024?'tablet':'desktop',viewport_width:w,viewport_height:h,device_pixel_ratio:devicePixelRatio||1,orientation:w>=h?'landscape':'portrait',coarse_pointer:matchMedia('(pointer:coarse)').matches}}
function buildExport(){const ex=new Date().toISOString();return{meta:{session_id:sessionId,...META,sound_preference_enabled:state.sound,device_context:deviceContext(),layout_changes:state.layout_changes,exported_at:ex},items:state.items,responses:state.responses,storyFacts:STORY_FACTS,scene_history:state.scene_history||[],colleague_interaction:state.colleague_interaction,supportEvents:state.supportEvents,supportCommitments:state.supportCommitments,teaching:state.teaching||null,student_dialogue166:state.student_dialogue166||null,totalScore:null,parent_interaction:state.parent_interaction,interaction_trace:state.interaction_trace,event_log:state.event_log,self_tests:runSelfTests()}}
function exportJson(){const blob=new Blob([JSON.stringify(buildExport(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${sessionId}-165-167-pc14.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500);log('export_json',{session_id:sessionId})}
function runSelfTests(){const tests=[
 ['165 concrete clarify',165,'你說的怪，是最後一題的分數怎麼算嗎？',4,{}],
 ['165 verify class',165,'那我們問問全班有沒有看見當時誰先舉手。',4,{}],
 ['165 answer problem',165,'是答案有問題嗎？',3,{}],
 ['165 vague clarify',165,'哪裡怪怪的？',3,{}],
 ['165 dismissive guard',165,'已經解釋過了，還有哪裡有疑惑嗎？',null,{}],
 ['165 unsupported resolution',165,'沒有要改掉啊，人家真的舉得比較快。',2,{}],
 ['166 explicit split',166,'那次比賽的事情老師下課會再跟你談，但現在這堂課該完成的作業還是要完成。',4,{}],
 ['166 contrast explore',166,'是不想寫作業，還是還在想積分的事情？',3,{}],
 ['166 command guard',166,'乖，作業要寫啦',null,{}],
 ['166 post contextual sequence',166,'我們還是要把作業寫完，心情不好的地方可以先寫下來，下課我們專門討論，好嗎？',3,{post_reveal:true}],
 ['167 recent school',167,'您好，我也正想找您聊一聊子安最近的狀況。',3,{}],
 ['167 full context',167,'我想跟您談談子安最近在學校的狀況，這幾天他又提到那次小組比賽。',4,{}],
 ['166 affective only',166,'對呀，因為老師在乎你的感受。',null,{two_sided:true}],
 ['166 invalidating guard',166,'為什麼還是很煩？不是解釋清楚了嗎',null,{}],
 ['166 blaming attribution',166,'是你偷懶不想寫作業？',1,{}],
 ['167 greeting only',167,'家長你好！',null,{}]
];return tests.map(([name,item,text,want,ctx])=>{const r=code(item,'TEST',text,ctx);return{name,pass:r.score===want,want,got:r.score,review_reason:r.review_reason}})}
function bindHotspots(){
 $('#teacherHotspot').addEventListener('click',()=>interact('導師','導師抬起手，示意孩子慢慢說。',()=>classmateReact(els.teacher)));
 $('#zianHotspot').addEventListener('click',()=>interact('子安','子安抿著嘴看了一眼黑板，又把視線移回你這邊。',()=>classmateReact(els.zian)));
 $('#peerAHotspot').addEventListener('click',()=>interact('佳恩','佳恩低頭在紙上畫了幾筆。',()=>scribble(true)));$('#peerAHotspot').addEventListener('dblclick',()=>interact('佳恩','佳恩把剛摺好的紙飛機往前射了出去，又把手收回去。',()=>throwPaperPlane(true)));
 $('#peerBHotspot').addEventListener('click',()=>interact('阿威','阿威敲了兩下鉛筆。',()=>pencilTap(true)));$('#peerCHotspot').addEventListener('click',()=>interact('小楓','小楓抬起手伸了伸肩膀，再回到學習單前。',()=>stretch(true)));$('#peerDHotspot').addEventListener('click',()=>interact('高個子同學','他抬起頭一下，又低頭看著桌面。',()=>doze(true)));
 $('#bagHotspot').addEventListener('click',()=>interact('書包',state.bag_down?'書包被扶正，剛露出來的紙又很心虛地縮回去了。':'書包「咚」地側倒，一張作業紙偷偷露出半張。',()=>{const b=els.bag;b.getAnimations().forEach(a=>a.cancel());const from=state.bag_down?'rotate(62deg) translate(7px,5px)':'rotate(0deg) translate(0,0)',to=state.bag_down?'rotate(0deg) translate(0,0)':'rotate(62deg) translate(7px,5px)';b.animate([{transform:from},{transform:to}],{duration:540,easing:'cubic-bezier(.2,.75,.25,1)',fill:'forwards'});if(els.bagPaper){els.bagPaper.animate([{opacity:state.bag_down?1:0,transform:state.bag_down?'translate(3px,3px)':'translate(0,0)'},{opacity:state.bag_down?0:1,transform:state.bag_down?'translate(0,0)':'translate(7px,-7px)'}],{duration:520,fill:'forwards'})}sparkAt(89,78,state.bag_down?'✓':'!');state.bag_down=!state.bag_down;state.interactive_state.bag=state.bag_down?'tipped':'upright';log('ambient_event',{type:state.bag_down?'bag_tip_over_paper_peek':'bag_restore_paper_hide',window:state.interaction_window})}));
 $('#plantHotspot').addEventListener('click',()=>interact('盆栽','葉片在花盆原地左右抖了幾下，像剛被手指碰到。',()=>{els.plant.getAnimations().forEach(a=>a.cancel());els.plant.animate([{transform:'rotate(0deg)'},{transform:'rotate(8deg)'},{transform:'rotate(-10deg)'},{transform:'rotate(6deg)'},{transform:'rotate(-3deg)'},{transform:'rotate(0deg)'}],{duration:980,easing:'ease-out'});sparkAt(8,77,'❋');log('ambient_event',{type:'plant_tap_sway_local',window:state.interaction_window})}));
 $('#curtainHotspot').addEventListener('click',()=>interact('窗簾','只有布簾本身被風掀起，窗框留在原地；布料晃兩下後落回來。',()=>{els.curtain.getAnimations().forEach(a=>a.cancel());els.curtain.animate([{transform:'translateY(0) skewX(-1deg)'},{transform:'translateY(-58px) skewX(8deg)',offset:.30},{transform:'translateY(-43px) skewX(-6deg)',offset:.52},{transform:'translateY(-18px) skewX(4deg)',offset:.74},{transform:'translateY(0) skewX(-1deg)'}],{duration:1350,easing:'cubic-bezier(.2,.75,.25,1)'});sparkAt(14,24,'~');setTimeout(()=>birdVisit(true),420);log('ambient_event',{type:'curtain_fabric_lift_only_with_bird_peek',window:state.interaction_window})}));
 $('#clock').addEventListener('click',()=>interact('時鐘','時鐘突然很有幹勁地晃了兩下。時間沒有真的變快，放心。',()=>{els.stage.classList.remove('giggle');void els.stage.offsetWidth;els.stage.classList.add('giggle');sparkAt(29,10,'⏱');setTimeout(()=>els.stage.classList.remove('giggle'),760);log('ambient_event',{type:'clock_giggle',window:state.interaction_window})}));
 $('#posterHotspot').addEventListener('click',()=>interact('班級海報','協尋海報晃了一下。鉛筆本人目前拒絕受訪。',()=>{document.getElementById('posterVisual').animate([{transform:'rotate(0)'},{transform:'rotate(-5deg)'},{transform:'rotate(4deg)'},{transform:'rotate(0)'}],{duration:720,easing:'ease-in-out'});sparkAt(92,14,'★');log('ambient_event',{type:'poster_wiggle',window:state.interaction_window})}));
 $('#bookcaseHotspot').addEventListener('click',()=>interact('書櫃',state.book_down?'紅棕色的書被扶正，旁邊的筆也跟著晃兩下。':'紅棕色的書「啪」地歪倒，旁邊的文具像被嚇到一樣抖了一下。',()=>{const b=els.book;b.getAnimations().forEach(a=>a.cancel());const from=state.book_down?'rotate(58deg) translate(8px,8px)':'rotate(0deg) translate(0,0)',to=state.book_down?'rotate(0deg) translate(0,0)':'rotate(58deg) translate(8px,8px)';b.animate([{transform:from},{transform:to}],{duration:560,easing:'cubic-bezier(.22,.72,.24,1)',fill:'forwards'});els.bookcase?.animate([{transform:'translateX(0)'},{transform:'translateX(-2px)'},{transform:'translateX(2px)'},{transform:'translateX(0)'}],{duration:380,easing:'ease-in-out'});sparkAt(91,28,state.book_down?'✓':'✦');state.book_down=!state.book_down;state.interactive_state.book=state.book_down?'leaning':'upright';log('ambient_event',{type:state.book_down?'shelf_book_tip_visible':'shelf_book_restore_visible',window:state.interaction_window})}));
}
if(els.callPhone==null){}
$('#callStage')?.addEventListener('click',e=>{if(e.target.closest('.call-phone')){e.stopPropagation();toast('通話紀錄會留在手機裡；只有下方按鈕會推進對話。',1500);log('phone_visual_tap',{event_type:'ambient_interaction'})}});
$('#soundToggle').onclick=()=>{state.sound=!state.sound;$('#soundToggle').textContent=state.sound?'♪':'♪×';$('#soundToggle').setAttribute('aria-pressed',String(state.sound));if(state.sound)tone('tap')};$('#motionToggle').onclick=()=>{state.motion_paused=!state.motion_paused;els.stage.classList.toggle('motion-paused',state.motion_paused);els.stage.getAnimations({subtree:true}).forEach(a=>state.motion_paused?a.pause():a.play());$('#motionToggle').textContent=state.motion_paused?'▶':'Ⅱ';$('#motionToggle').setAttribute('aria-pressed',String(state.motion_paused));log('motion_toggle',{paused:state.motion_paused})};$('#menuBtn').onclick=e=>{e.stopPropagation();$('#menuPop').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!e.target.closest('.menu'))$('#menuPop').classList.add('hidden')});$('#exportBtn').onclick=exportJson;$('#restartBtn').onclick=()=>{if(confirm('要重新開始嗎？目前未匯出的作答會清除。'))location.reload()};$('#versionBtn').onclick=()=>{$('#versionPre').textContent=JSON.stringify({...META,self_tests:runSelfTests()},null,2);$('#versionModal').classList.remove('hidden')};$('#closeVersion').onclick=()=>$('#versionModal').classList.add('hidden');$('#versionModal').addEventListener('click',e=>{if(e.target===$('#versionModal'))$('#versionModal').classList.add('hidden')});
const API={STORY_FACTS,throwPaperPlane,birdVisit,interact,scribble,state,META,els,sessionId,t,log,esc,code,code165,code166,code167,parentReply,runSelfTests,buildExport,responseUI,setPhase,contextualReply166,showTeacher,showStudent,showColleague,narration,dock,transition,begin166,beginColleague,begin167,colleagueChoice};
globalThis.CLASS5_REFERENCE=API;C5_EXT.installStage?.(API);C5_SCENES.install(API);C5_REFINE.install(API);C5_CAT.install(API);
let lastLayout='';function trackLayout(){const d=deviceContext(),sig=JSON.stringify(d);if(sig!==lastLayout){lastLayout=sig;state.layout_changes.push({t_ms:t(),...d})}}addEventListener('resize',()=>{clearTimeout(window.__layoutT);window.__layoutT=setTimeout(trackLayout,180)});trackLayout();bindHotspots();const tests=runSelfTests();console.table(tests);if(tests.some(x=>!x.pass))setTimeout(()=>toast('評分自我檢查未通過，請勿用於正式試測',4000),500);intro();requestAnimationFrame(()=>{els.openingCurtain?.classList.add('play');log('opening_curtain',{event_type:'ambient_interaction'});setTimeout(()=>els.openingCurtain?.classList.add('done'),1900);setTimeout(()=>els.openingCurtain?.remove(),2350)});
})();
